version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: ./back
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/database
    command: /bin/sh -c "go run github.com/steebchen/prisma-client-go db push && /app"

volumes:
  db-data:
